# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PrivacyDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PrivacyDemo
  pod 'PureLayout', :path => '../PrivacyPods/PureLayout'
  pod 'AFNetworking', :path => '../PrivacyPods/AFNetworking'

end
