# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PrivacyDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PrivacyDemo
  pod 'PureLayout', :path => '../'
  pod 'AFNetworking', :path => '../'
#  pod 'AFNetworking', :git => 'https://github.com/gzx543097079/AppStorePrivacyInfo.git', :tag => 'AFNetworking-4.0.1.1'
#  pod 'PureLayout', :git => 'https://github.com/gzx543097079/AppStorePrivacyInfo.git', :tag => 'PureLayout-3.1.9'
  
end
